### ISSUE TITLE
Document how to run alembic migrations

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/tokenserver#162]
Migrations don't seem to be ran automatically. Until they do, the README should mention the need to run the migration tool in between releases and how to run them.

**Comment by 0x0ptr** [comment]
Continuing here since the other thread was closed.

FYI, I am using  https://github.com/mozilla-services/tokenserver/archive/1.5.0.tar.gz
Installed on Arch Linux from https://aur.archlinux.org/packages/python2-tokenserver/

Tried running the migration tool. Several issues:
1. alembic.init does not have "token_ini" setting. Fixed it locally
2. env.py assumes the name of the ini file is tokenserver.ini. Fixed locally:

`diff --git a/tokenserver/assignment/sqlnode/migrations/env.py b/tokenserver/assignment/sqlnode/migrations/env.py
index c33444e..8cc45ef 100644
--- a/tokenserver/assignment/sqlnode/migrations/env.py
+++ b/tokenserver/assignment/sqlnode/migrations/env.py
@@ -30,6 +30,8 @@ ini_file = find_config_file(config.get_main_option("token_ini"))
 settings = {}
 load_into_settings(ini_file, settings)

+ini_file_base_name = os.path.basename(ini_file)
+sqluri_key = os.path.splitext(ini_file_base_name)[0] + '.sqluri'

 def run_migrations_offline():
     """Run migrations in 'offline' mode.
@@ -43,7 +45,7 @@ def run_migrations_offline():
     script output.

     """
-    url = settings["tokenserver.sqluri"]
+    url = settings[sqluri_key]
     context.configure(url=url)

     with context.begin_transaction():
@@ -57,7 +59,8 @@ def run_migrations_online():
     and associate a connection with the context.

     """
-    url = settings["tokenserver.sqluri"]
+    print(settings.keys())
+    url = settings[sqluri_key]
     engine = create_engine(url, poolclass=NullPool)
     connection = engine.connect()
     context.configure(
`
3. When I run it now I get the following error:

`
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE users, nodes
        SET users.nodeid = nodes.id
        WHERE users.node = nodes.node]
`

Full stack trace:

`
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 17d209a72e2f, add replaced_at_idx
INFO  [alembic.runtime.migration] Running upgrade 17d209a72e2f -> 3d5af3924466, drop clientstate_idx
INFO  [alembic.runtime.migration] Running upgrade 3d5af3924466 -> 846f28d1b6f, add nodeid column
INFO  [alembic.runtime.migration] Running upgrade 846f28d1b6f -> 6569dd9a060, populate nodeid column and index
Traceback (most recent call last):
  File "/usr/bin/alembic2", line 11, in <module>
    load_entry_point('alembic==1.3.1', 'console_scripts', 'alembic')()
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 575, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 569, in main
    self.run_cmd(cfg, options)
  File "/usr/lib/python2.7/site-packages/alembic/config.py", line 549, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/lib/python2.7/site-packages/alembic/command.py", line 298, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/site-packages/alembic/script/base.py", line 489, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/site-packages/alembic/util/compat.py", line 239, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "tokenserver/assignment/sqlnode/migrations/env.py", line 79, in <module>
    run_migrations_online()
  File "tokenserver/assignment/sqlnode/migrations/env.py", line 72, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 846, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 518, in run_migrations
    step.migration_fn(**kw)
  File "/home/user123/tmp/tokenserver/tokenserver/assignment/sqlnode/migrations/versions/6569dd9a060_populate_nodeid_column_and_index.py", line 33, in upgrade
    """.strip())
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/usr/lib/python2.7/site-packages/alembic/operations/ops.py", line 2225, in execute
    return operations.invoke(op)
  File "/usr/lib/python2.7/site-packages/alembic/operations/base.py", line 345, in invoke
    return fn(self, operation)
  File "/usr/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 176, in execute_sql
    operation.sqltext, execution_options=operation.execution_options
  File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 137, in execute
    self._exec(sql, execution_options)
  File "/usr/lib/python2.7/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ",": syntax error
[SQL: UPDATE users, nodes
        SET users.nodeid = nodes.id
        WHERE users.node = nodes.node]
(Background on this error at: http://sqlalche.me/e/e3q8)
`
I am not an SQL expert but as far as I can tell you cannot have two tables (users, nodes) in the UPDATE arguments.
I believe you have to provide a statement in the "SET" clause that will fetch data from another table. However, don't know how to fix this since I don't know what that statement would be....

**Comment by alexfornuto** [comment]
I could also use some help updating my DB to fix this issue, hopefully without needing to install alembic...

**Comment by rfk** [comment]
> hopefully without needing to install alembic...

The details of the migration are in [this file](https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/assignment/sqlnode/migrations/versions/75e8ca84b0bc_add_keys_changed_at_column.py) if you're curious, but they basically boil down to "add a nullable bigint `keys_changed_at` column to the `users` table". Depending on your SQL dialect I would expect something like this (untested!) alter statement to get things back up and running:

```
ALTER TABLE users ADD COLUMN keys_changed_at BIGINT UNSIGNED DEFAULT NULL;
```

Hope this helps!

**Comment by alexfornuto** [comment]
Thanks @rfk  - I removed the columns added with [these commands](https://github.com/mozilla-services/syncserver/pull/193#commitcomment-36884169) and ran your command. Running syncserver from the repo still fails as described [here](https://github.com/mozilla-services/syncserver/issues/202) - running the aur package [here](https://aur.archlinux.org/packages/mozilla-firefox-sync-server/) still yields the `KeyError: 'keys_changed_at'` error.

**Comment by rfk** [comment]
Are you using the default mozilla-hosted accounts server, or hosting your own accounts server as well? Please paste the full traceback and I'll see if I can think of anything else to try.

**Comment by alexfornuto** [comment]
I'm using Mozilla's account server.

Logs from the AUR version:

```
 ERROR:mozsvc:Uncaught exception while processing request:
 GET https://sync.fornuto.com:5000/token/1.0/sync/1.5
 Uncaught exception:
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 59, in log_uncaught_exceptions_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 26, in catch_backend_errors_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
     response = _error_handler(request, exc)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
     reraise(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
     registry, request, context, context_iface, view_name
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
     response = view_callable(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in __call__
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
     result = view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
     response = view(request)
   File "/usr/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
     response = view_(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/views.py", line 384, in return_token
     if keys_changed_at > user['keys_changed_at']:
 <type 'exceptions.KeyError'>
 KeyError('keys_changed_at',)
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
     response = self.execution_policy(environ, self)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
     return request.invoke_exception_view(reraise=True)
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
     reraise_(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
     return router.invoke_request(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
     response = handle_request(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/tweens.py", line 15, in set_x_timestamp_header_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 123, in convert_non_json_responses_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 99, in convert_cornice_errors_to_respcodes_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 53, in set_default_accept_header_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 30, in set_x_timestamp_header_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 94, in fuzz_backoff_headers_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 59, in log_uncaught_exceptions_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 26, in catch_backend_errors_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
     response = _error_handler(request, exc)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
     reraise(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
     registry, request, context, context_iface, view_name
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
     response = view_callable(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in __call__
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
     result = view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
     response = view(request)
   File "/usr/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
     response = view_(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/views.py", line 384, in return_token
     if keys_changed_at > user['keys_changed_at']:
 KeyError: 'keys_changed_at'
```

The only output I got from the cloned repo and `make serve` is what's posted [here](https://github.com/mozilla-services/syncserver/issues/202) - if there's a way to get more verbose debugging out of it I haven't seen it documented.


Log from

**Comment by alexfornuto** [comment]
I'm using Mozilla's account server.

Logs from the AUR version:

```
 ERROR:mozsvc:Uncaught exception while processing request:
 GET https://$PUBLIC_URL.com:5000/token/1.0/sync/1.5
 Uncaught exception:
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 59, in log_uncaught_exceptions_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 26, in catch_backend_errors_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
     response = _error_handler(request, exc)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
     reraise(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
     registry, request, context, context_iface, view_name
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
     response = view_callable(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in __call__
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
     result = view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
     response = view(request)
   File "/usr/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
     response = view_(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/views.py", line 384, in return_token
     if keys_changed_at > user['keys_changed_at']:
 <type 'exceptions.KeyError'>
 KeyError('keys_changed_at',)
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 270, in __call__
     response = self.execution_policy(environ, self)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 279, in default_execution_policy
     return request.invoke_exception_view(reraise=True)
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 778, in invoke_exception_view
     reraise_(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 277, in default_execution_policy
     return router.invoke_request(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 249, in invoke_request
     response = handle_request(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/tweens.py", line 15, in set_x_timestamp_header_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 123, in convert_non_json_responses_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 99, in convert_cornice_errors_to_respcodes_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 53, in set_default_accept_header_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/syncstorage/tweens.py", line 30, in set_x_timestamp_header_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 94, in fuzz_backoff_headers_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 59, in log_uncaught_exceptions_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/mozsvc/tweens.py", line 26, in catch_backend_errors_tween
     return handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 43, in excview_tween
     response = _error_handler(request, exc)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 17, in _error_handler
     reraise(*exc_info)
   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 41, in excview_tween
     response = handler(request)
   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 148, in handle_request
     registry, request, context, context_iface, view_name
   File "/usr/lib/python2.7/site-packages/pyramid/view.py", line 667, in _call_view
     response = view_callable(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 169, in __call__
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 188, in attr_view
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
     return view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
     result = view(context, request)
   File "/usr/lib/python2.7/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
     response = view(request)
   File "/usr/lib/python2.7/site-packages/cornice/service.py", line 514, in wrapper
     response = view_(request)
   File "/usr/lib/python2.7/site-packages/tokenserver/views.py", line 384, in return_token
     if keys_changed_at > user['keys_changed_at']:
 KeyError: 'keys_changed_at'
```

The only output I got from the cloned repo and `make serve` is what's posted [here](https://github.com/mozilla-services/syncserver/issues/202) - if there's a way to get more verbose debugging out of it I haven't seen it documented.

**Comment by rfk** [comment]
Thanks. At a guess I'd say the AUR version is missing the fix from https://github.com/mozilla-services/syncserver/pull/193, and might be fixed if updated to use the latest master of the syncserver repo. The timeout errors from `make serve` are not something seen before unfortunately; @jrconlin was working on getting some of this to run under different setups, JR, does anything from https://github.com/mozilla-services/syncserver/issues/202 look familiar?

**Comment by jrconlin** [comment]
I've not seen timeouts like that. I commented on the other bug that I'm confused and a bit concerned that a sqlite file is being generated if a mariadb DSN is specified. 

As for the db update, I'm still digging into the alembic updater code, and it's... very clever.

**Comment by alexfornuto** [comment]
I [commented](https://github.com/mozilla-services/syncserver/issues/202#issuecomment-586060835) on the other bug to clarify that I've tried both MySQL (mariadb) and sqlite separately, with the same results.
