### ISSUE TITLE
Cannot build loadtest on 1.5.6

### ISSUE THREAD

**Issue by jrgm** [mozilla-services/tokenserver#186]
This is really an issue with `loads`, but I get the failure below. Not a problem immediately, since I should use the pre-pypy version to do a baseline test first anyways.
```
$ make build
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future ../local/bin/pip install pexpect
Requirement already satisfied: pexpect in /Users/jrgm/github/mozilla-services/tokenserver/local/site-packages (4.8.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/jrgm/github/mozilla-services/tokenserver/local/site-packages (from pexpect) (0.6.0)
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future ../local/bin/pip install https://github.com/mozilla-services/loads/archive/master.zip
Collecting https://github.com/mozilla-services/loads/archive/master.zip
  Using cached https://github.com/mozilla-services/loads/archive/master.zip
Collecting pyzmq
  Using cached pyzmq-19.0.1-pp27-pypy_73-macosx_10_9_x86_64.whl (543 kB)
Collecting psutil
  Using cached psutil-5.7.0.tar.gz (449 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/jrgm/github/mozilla-services/tokenserver/local/bin/pypy -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-install-tFoS8I/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-install-tFoS8I/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-pip-egg-info-Er0h9Q
         cwd: /private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-install-tFoS8I/psutil/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-install-tFoS8I/psutil/setup.py", line 46, in <module>
        from _compat import PY3  # NOQA
      File "/private/var/folders/vw/_p6z97yd45l6mk603v1mckth0000gn/T/pip-install-tFoS8I/psutil/psutil/_compat.py", line 120, in <module>
        "broken / incompatible Python implementation, see: "
    RuntimeError: broken / incompatible Python implementation, see: https://github.com/giampaolo/psutil/issues/1659
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [build] Error 1
$ 
```

**Comment by tublitzed** [comment]
@jrgm - can you confirm this was resolved [here](https://github.com/mozilla-services/tokenserver/pull/189), or should we keep this one open?

**Comment by jrgm** [comment]
I haven't researched this further but I don't think it would be fixed by the `cffi` issue. The actual fix will probably be a change to `loads` for an updated version, or other fix.

**Comment by rfk** [comment]
FWIW the linked issue at https://github.com/giampaolo/psutil/issues/1659 suggests that this may be fixed in the most recent release of PyPy. But I don't recall the details how how we pick up the version of pypy to use in the docker image.
