### ISSUE TITLE
Load tests need update to molotov/loads-broker compatibility

### ISSUE THREAD

**Issue by karlht** [mozilla-services/tokenserver#97]
The load tests in the `loadtests` directory were originally written for Loads v1, which is no longer in use.

The two load testing frameworks currently in use in Firefox Test Engineering are https://github.com/loads/molotov and https://github.com/loads/loads-broker -- the load tests here need an upgrade to be compatible with either or both of these frameworks.

**Comment by tarekziade** [comment]
First version ported at https://github.com/mozilla-services/tokenserver-loadtests/blob/master/loadtest.py

Unfortunately PyBrowserId is blocking (uses requests) so I need to port its calls using asynciohttp, that's my next step

**Comment by tarekziade** [comment]
@karlht you can run the loadtest from your laptop with:

```bash
$ pip install molotov
$ moloslave https://github.com/mozilla-services/tokenserver-loadtests smoke
```

If you have any issue, please comment in the new repo. I wil leave this bug open so we can retire /loadtests in this repo once we're happy

**Comment by karlht** [comment]
```
[0] 12:29 (ttys002) kthiessen@kthiessen-16107:~ 502$ moloslave https://github.com/mozilla-services/tokenserver-loadtests smoke
Working directory is /var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox
Cloning into '.'...
remote: Counting objects: 22, done.        
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22        
Unpacking objects: 100% (22/22), done.
Already using interpreter /usr/local/opt/python3/bin/python3.6
Using base prefix '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6'
New python executable in /private/var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox/venv/bin/python3.6
Also creating executable in /private/var/folders/tr/zhjwv42949g6vnw9p1bgw73w0000gp/T/tmp7dlpypox/venv/bin/python
Installing setuptools, pip, wheel...done.
Running: molotov -r 1 loadtest.py
**** Molotov v1.4. Happy breaking! ****
Traceback (most recent call last):
  File "/usr/local/bin/moloslave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/molotov/slave.py", line 118, in main
    run_test(**config['molotov']['tests'][args.run])
  File "/usr/local/lib/python3.6/site-packages/molotov/slave.py", line 59, in run_test
    return run(args)
  File "/usr/local/lib/python3.6/site-packages/molotov/run.py", line 179, in run
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "loadtest.py", line 9, in <module>
ModuleNotFoundError: No module named 'browserid'
```

**Comment by karlht** [comment]
Are we lacking a requirement here?

**Comment by karlht** [comment]
Will comment in the new repo as well.

**Comment by karlht** [comment]
Closing, now that the issue is resolved.
